//! Static list of settings exposed in the /settings menu.
//!
//! The `ALL_SETTINGS` array is generated by the `define_settings!` macro in
//! `defs.rs` — that's the single source of truth for both schema and apply
//! handler. Do not add settings here; add them in `defs.rs`.

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum Category {
    Model,
    Providers,
    Agent,
    ToolLimits,
    Appearance,
    Plugins,
    Voice,
}

impl Category {
    pub fn label(&self) -> &'static str {
        match self {
            Category::Model => "Model",
            Category::Providers => "Providers",
            Category::Agent => "Agent",
            Category::ToolLimits => "Tool Limits",
            Category::Appearance => "Appearance",
            Category::Plugins => "Plugins",
            Category::Voice => "Voice",
        }
    }
}

pub(crate) const CATEGORIES: [Category; 7] = [
    Category::Model,
    Category::Providers,
    Category::Agent,
    Category::ToolLimits,
    Category::Appearance,
    Category::Plugins,
    Category::Voice,
];

pub(crate) enum EditorKind {
    Cycler(&'static [&'static str]),
    ModelPicker,
    ThemePicker,
    /// Picks a whisper STT model (`*.bin`) from
    /// `~/.synaps-cli/models/whisper/`. Persisted as `voice_stt_model_path`.
    WhisperModelPicker,
    Text { numeric: bool },
}

pub(crate) struct SettingDef {
    pub key: &'static str,
    pub label: &'static str,
    pub category: Category,
    pub editor: EditorKind,
    /// Kept on each setting so the settings modal can render an inline
    /// help line later without reshuffling the schema. Referenced by
    /// drafts of the per-setting hint UI; retain even while unused.
    #[allow(dead_code)]
    pub help: &'static str,
}

// Re-export the macro-generated schema so existing call sites keep working.
pub(crate) use super::defs::ALL_SETTINGS;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_setting_belongs_to_known_category() {
        for def in ALL_SETTINGS {
            assert!(CATEGORIES.contains(&def.category));
        }
    }

    #[test]
    fn plugins_category_is_present() {
        assert!(CATEGORIES.contains(&Category::Plugins));
    }

    #[test]
    fn plugins_category_label() {
        assert_eq!(Category::Plugins.label(), "Plugins");
    }

    #[test]
    fn voice_category_is_present() {
        assert!(CATEGORIES.contains(&Category::Voice));
    }

    #[test]
    fn voice_category_label() {
        assert_eq!(Category::Voice.label(), "Voice");
    }

    #[test]
    fn voice_settings_belong_to_voice_category() {
        let voice_keys = ["voice_toggle_key", "voice_language"];
        for def in ALL_SETTINGS {
            if voice_keys.contains(&def.key) {
                assert_eq!(def.category, Category::Voice, "setting '{}' should be in Voice", def.key);
            }
        }
        // Both keys must exist.
        let keys: Vec<&str> = ALL_SETTINGS.iter().map(|d| d.key).collect();
        for k in voice_keys {
            assert!(keys.contains(&k), "missing voice setting: {}", k);
        }
    }
}
